---
title: "projet"
author: "Amélie GOUTARD"
date: '2022-04-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importation librairies
```{r}
library(tidyverse)
library(lubridate)
library(forecast)
library(plyr)
library(plotly)
library(xts)
```

# Importation et traitements des données 
Source des données : https://www.insee.fr/fr/statistiques/series/102765746
```{r}
## on importe
caracteristiques <- read_delim("caractéristiques.csv", delim =";")
v_mensuelles <- read_delim("valeurs_mensuelles.csv", delim =",")
head(caracteristiques)
head(v_mensuelles)

## on garde uniquement les colonnes utiles
vm_depenses <- v_mensuelles %>% 
  select("Libellé","Situation mensuelle du budget de l'État - Dépenses - Cumul depuis le début de l'année" )

colnames(vm_depenses) <- c("date", "depenses")

## on veut la colonne date au format date
vm_depenses$date <- ym(vm_depenses$date)

## si on ne veut pas cumulé
for (j in 1:13){
  for (i in 2:12){
     vm_depenses[i+((j-1)*12),2]<-vm_depenses[i+((j-1)*12),2]-sum(vm_depenses[(1+((j-1)*12)):((i-1)+((j-1)*12)),2])
   }
}

```



```{r}
# month.plot 
ts = ts(vm_depenses$depenses, frequency=12)
forecast::ggmonthplot(ts)
```


```{r}
vm_depenses%>% plot_ly(type = "scatter", mode = "lines") %>% add_trace( x = ~date, y=~depenses) 
plot(xts(vm_depenses$depenses, vm_depenses$date))

ts.depenses = xts(vm_depenses$depenses, vm_depenses$date)

ts.depenses %>% 
  ggtsdisplay(
    plot.type = "scatter"
  )
# tendance polynomiale?

ts.depenses %>% 
  diff(
    differences = 1
  ) %>% 
  ggtsdisplay(
    plot.type = "scatter"
  )

# Pas degré 1

ts.depenses %>% 
  diff(
    differences = 2
  ) %>% 
  ggtsdisplay(
    plot.type = "scatter"
  )

```


```{r}

```



Etapes à effectuer:
  - Stat desc
  - Première ACF
  - Opérateur différence : détecter tendance et saisonnalité 
  -Suppression pour arriver à series stationnaires
  - Reg lin 
  - Etudes des résidus
  - ACF + PACF pour déterminer ordre des processus
