---
title: "Projet_SerieTemp"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importation librairies
```{r}
library(ggplot2)
library(timeDate)
library(forecast)
library(dplyr)
library(plyr) 
```

## Importation des données 
Source des données : https://www.insee.fr/fr/statistiques/series/102765746
```{r}
caracteristiques <- read.csv("caractéristiques.csv", sep =";")
v_mensuelles <- read.csv("valeurs_mensuelles.csv", sep =",")
head(caracteristiques)
head(v_mensuelles)
```
Nous concentrons l'étude sur les dépenses:
```{r}
dépenses <- v_mensuelles %>% select(LibellÃ., Situation.mensuelle.du.budget.de.l.Ã.tat...DÃ.penses...Cumul.depuis.le.dÃ.but.de.l.annÃ.e)
rename(dépenses, c("LibellÃ." = "Date", "Situation.mensuelle.du.budget.de.l.Ã.tat...DÃ.penses...Cumul.depuis.le.dÃ.but.de.l.annÃ.e" = "Dépenses_cumulées"))
```

Etapes à effectuer:
  -Stat desc
  -Première ACF
  -Opérateur différence : détecter tendance et saisonnalité 
  -Suppression pour arriver à series stationnaires
  -Reg lin 
  -Etudes des résidus
  -ACF + PACF pour déterminer ordre des processus
  ...